# Theme author
ThemeAuthor="lunarplums"

# Theme description
ThemeDescription="Windows XP"

# Look
Look=pixmap

# Horizontal dialog window border
DlgBorderSizeX=3
 # 0-128

# Vertical dialog window border
DlgBorderSizeY=3 # 0-128

# Horizontal window border
BorderSizeX=3 # 0-128

# Vertical window border
BorderSizeY=3 # 0-128

# Resize corner width
CornerSizeX=6 # 0-64

# Resize corner height
CornerSizeY=6 0-64

# Shaped pixmaps protect client window
ShapesProtectClientWindow=1 # 0 / 1

# Fill highlight rectangle
QuickSwitchFillSelection=0 # 0 / 1

# Show text above icons
QuickSwitchTextFirst=0 # 0 / 1

# Border size of quick-switch icons
QuickSwitchIconBorder=4 # 0-30

# Size of icon margins of quick-switch icons
QuickSwitchIconMargin=4 # 0-30

# Horizontal margin of quick-switch window
QuickSwitchHorzMargin=0 # 0-30

# Vertical margin of quick-switch window
QuickSwitchVertMargin=10 # 0-30

# Size of the quick-switch window separator
QuickSwitchSeparatorSize=20 0-30

#Surround the tray with plastic border.
TrayDrawBevel=1 # 0/1

#Maximum scaled height of tray icons.
TrayIconMaxHeight=21 # [16-128]

#Maximum scaled width of tray icons.
TrayIconMaxWidth=21 # [16-128]

# Horizontal scrollbar button size
ScrollBarX=16 # 0-100

# Vertical scrollbar button size
ScrollBarY=16 # 0-100

# Menu icon size
MenuIconSize=12 # 8-128

# Dimension of the small icons
SmallIconSize=16 # 8-128

# Dimension of the large icons
LargeIconSize=32 # 8-128

# Dimension of the extra large icons
HugeIconSize=32 # 8-128

#Display Menu Icon
ShowMenuButtonIcon=1

# Does the theme support the "O" title bar button images (for mouse rollover)
RolloverButtonsSupported=1 # 0 / 1

# Titlebar buttons supported by theme (x, m, i, r, h, s, d)
TitleButtonsSupported="shxmi"

# Titlebar buttons from left to right (x=close, m=max, i=min, h=hide, r=rollup, s=sysmenu)
TitleButtonsLeft="s"

# Titlebar buttons from right to left (x=close, m=max, i=min, h=hide, r=rollup, s=sysmenu)
TitleButtonsRight="xmi" 

# Title bar height
TitleBarHeight=26 # 0-128

# Title bar join right
TitleBarJoinRight=1 # 0 / 1

# Title bar join left
TitleBarJoinLeft=0 # 0 / 1

# Title bar text position
TitleBarJustify=0 # 0-100

# Title bar text horizontal offset
TitleBarHorzOffset=0 # -128-128

# Title bar text vertical offset
TitleBarVertOffset=0 # -128-128

# List of gradient images in the current theme
Gradients="frameAT.xpm frameAB.xpm titleAB.xpm titleIB.xpm titleAT.xpm titleIT.xpm"

#Colors

    ColorDialog = "#ffffff"
    #Background of dialog windows.

    ColorNormalBorder = "#ffffff"
    #Border of inactive windows.

    ColorActiveBorder = "#ffffff"
    #Border of active windows.

    ColorNormalButton = "#ffffff"
    #Background of regular buttons.

    ColorNormalButtonText = "#434C5E"
    #Textcolor of regular buttons.

    ColorActiveButton = "#ffffff"
    #Background of pressed buttons.

    ColorActiveButtonText = "#434C5E"
    #Textcolor of pressed buttons.

    ColorNormalTitleButton = "#ffffff"
    #Background of titlebar buttons.

    ColorNormalTitleButtonText = "#434C5E"
    #Textcolor of titlebar buttons.

    ColorToolButton = ""
    #Background of toolbar buttons, ColorNormalButton is used if empty.

    ColorToolButtonText = ""
    #Textcolor of toolbar buttons, ColorNormalButtonText is used if empty.

    ColorNormalWorkspaceButton = ""
    #Background of workspace buttons, ColorNormalButton is used if empty.

    ColorNormalWorkspaceButtonText = ""
    #Textcolor of workspace buttons, ColorNormalButtonText is used if empty.

    ColorActiveWorkspaceButton = ""
    #Background of the active workspace button, ColorActiveButton is used if empty.

    ColorActiveWorkspaceButtonText = ""
    #Textcolor of the active workspace button, ColorActiveButtonText is used if empty.

    ColorNormalTitleBar = "#ffffff"
    #Background of the titlebar of regular windows.

    ColorNormalTitleBarText = "#ffffff"
    #Textcolor of the titlebar of regular windows.

    ColorNormalTitleBarShadow = ""
    #Textshadow of the titlebar of regular windows.

    ColorActiveTitleBar = "#434C5E"
    #Background of the titlebar of active windows.

    ColorActiveTitleBarText = "#ffffff"
    #Textcolor of the titlebar of active windows.

    ColorActiveTitleBarShadow = "#000000"
    #Textshadow of the titlebar of active windows.

    ColorNormalMinimizedWindow = "#ffffff"
    #Background for mini icons of regular windows.

    ColorNormalMinimizedWindowText = "#434C5E"
    #Textcolor for mini icons of regular windows.

    ColorActiveMinimizedWindow = "#ffffff"
    #Background for mini icons of active windows.

    ColorActiveMinimizedWindowText = "#434C5E"
    #Textcolor for mini icons of active windows.

    ColorNormalMenu = "#ffffff"
    #Background of pop-up menus.

    ColorNormalMenuItemText = "#434C5E"
    #Textcolor of regular menu items.

    ColorActiveMenuItem = "#aabae7"
    #Background of selected menu item, leave empty to force transparency.

    ColorActiveMenuItemText = "#434C5E"
    #Textcolor of selected menu items.

    ColorDisabledMenuItemText = "#9e9ca4"
    #Textcolor of disabled menu items.

    ColorDisabledMenuItemShadow = ""
    #Shadow of regular menu items.

    ColorMoveSizeStatus = "#ffffff"
    #Background of move/resize status window.

    ColorMoveSizeStatusText = "#434C5E"
    #Textcolor of move/resize status window.

    ColorQuickSwitch = "#ffffff"
    #Background of the quick switch window.

    ColorQuickSwitchText = "#434C5E"
    #Textcolor in the quick switch window.

    ColorQuickSwitchActive = "#aabae7"
    #Rectangle arround the active icon in the quick switch window.

    ColorDefaultTaskBar = "#ffffff"
    #Background of the taskbar.

    ColorNormalTaskBarApp = "#ffffff"
    #Background for task buttons of regular windows.

    ColorNormalTaskBarAppText = "#434C5E"
    #Textcolor for task buttons of regular windows.

    ColorActiveTaskBarApp = "#ffffff"
    #Background for task buttons of the active window.

    ColorActiveTaskBarAppText = "#434C5E"
    #Textcolor for task buttons of the active window.

    ColorMinimizedTaskBarApp = "#aabae7"
    #Background for task buttons of minimized windows.

    ColorMinimizedTaskBarAppText = "#434C5E"
    #Textcolor for task buttons of minimized windows.

    ColorInvisibleTaskBarApp = "#9e9ca4"
    #Background for task buttons of windows on other workspaces.

    ColorInvisibleTaskBarAppText = "#434C5E"
    #Textcolor for task buttons of windows on other workspaces.

    ColorScrollBar = "#aabae7"
    #Scrollbar background (sliding area).

    ColorScrollBarSlider = "#ffffff"
    #Background of the slider button in scrollbars.

    ColorScrollBarButton = "#ffffff"
    #Background of the arrow buttons in scrollbars.

    ColorScrollBarArrow = "#ffffff"
    #Background of the arrow buttons in scrollbars (obsolete).

    ColorScrollBarButtonArrow = "#434C5E"
    #Color of active arrows on scrollbar buttons.

    ColorScrollBarInactiveArrow = "#9e9ca4"
    #Color of inactive arrows on scrollbar buttons.

    ColorListBox = "#ffffff"
    #Background of listboxes.

    ColorListBoxText = "#434C5E"
    #Textcolor in listboxes.

    ColorListBoxSelection = "#9e9ca4"
    #Background of selected listbox items.

    ColorListBoxSelectionText = "#434C5E"
    #Textcolor of selected listbox items.

    ColorToolTip = "#ffffff"
    #Background of tooltips.

    ColorToolTipText = "#434C5E"
    #Textcolor of tooltips.

    ColorLabel = "#ffffff"
    #Background of labels, leave empty to force transparency.

    ColorLabelText = "#434C5E"
    #Textcolor of labels.

    ColorInput = "#434C5E"
    #Background of text entry fields (e.g. the addressbar).

    ColorInputText = "#434C5E"
    #Textcolor of text entry fields (e.g. the addressbar).

    ColorInputSelection = "#9e9ca4"
    #Background of selected text in an entry field.

    ColorInputSelectionText = "#434C5E"
    #Selected text in an entry field.

    ColorClock = "#ffffff"
    #Background of non-LCD clock, leave empty to force transparency.

    ColorClockText = "#434C5E"
    #Background of non-LCD monitor.

    ColorApm = "#434C5E"
    #Background of battery monitor, leave empty to force transparency.

    ColorApmText = "rgb:00/FF/00"
    #Textcolor of battery monitor.

    ColorApmBattary = "rgb:FF/FF/00"
    #Color of battery monitor when discharging.

    ColorApmLine = "rgb:00/FF/00"
    #Color of battery monitor when charging.

    ColorApmGraphBg = "#434C5E"
    #Background color for graph mode.

    ColorCPUStatusUser = "rgb:00/FF/00"
    #User load on the CPU monitor.

    ColorCPUStatusSystem = "rgb:FF/00/00"
    #System load on the CPU monitor.

    ColorCPUStatusInterrupts = "rgb:FF/FF/00"
    #Interrupts on the CPU monitor.

    ColorCPUStatusIoWait = "rgb:60/00/60"
    #IO Wait on the CPU monitor.

    ColorCPUStatusSoftIrq = "rgb:00/FF/FF"
    #Soft Interrupts on the CPU monitor.

    ColorCPUStatusNice = "rgb:00/00/FF"
    #Nice load on the CPU monitor.

    ColorCPUStatusIdle = "#434C5E"
    #Idle (non) load on the CPU monitor, leave empty to force transparency.

    ColorCPUStatusSteal = "rgb:FF/8A/91"
    #Involuntary Wait on the CPU monitor.

    ColorCPUStatusTemp = "rgb:60/60/C0"
    #Temperature of the CPU.

    ColorMEMStatusUser = "rgb:40/40/80"
    #User program usage in the memory monitor.

    ColorMEMStatusBuffers = "rgb:60/60/C0"
    #OS buffers usage in the memory monitor.

    ColorMEMStatusCached = "rgb:80/80/FF"
    #OS cached usage in the memory monitor.

    ColorMEMStatusFree = "#434C5E"
    #Free memory in the memory monitor.

    ColorNetSend = "rgb:FF/FF/00"
    #Outgoing load on the network monitor.

    ColorNetReceive = "rgb:FF/00/FF"
    #Incoming load on the network monitor.

    ColorNetIdle = "#434C5E"
    #Idle (non) load on the network monitor, leave empty to force transparency.

    ColorApmBattery = rgb:FF/FF/00
    #Color of battery monitor in battery mode.


# Font Specification
    TitleFontNameXft =					"Tahoma:size=9:bold,MS UI Gothic:size=9:bold"
    MenuFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
    StatusFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
    QuickSwitchFontNameXft =		    "Tahoma:size=9,MS UI Gothic:size=9"
    NormalButtonFontNameXft =			"Tahoma:size=9,MS UI Gothic:size=9"
    ActiveButtonFontNameXft =		    "Tahoma:size=9,MS UI Gothic:size=9"
    NormalTaskBarFontNameXft =			"Tahoma:size=9,MS UI Gothic:size=9"
    ActiveTaskBarFontNameXft =			"Tahoma:size=9,MS UI Gothic:size=9"
    ToolButtonFontNameXft =				"Tahoma:size=9,MS UI Gothic:size=9"
    NormalWorkspaceFontNameXft =	    "Tahoma:size=9,MS UI Gothic:size=9"
    ActiveWorkspaceFontNameXft =		"Tahoma:size=9,MS UI Gothic:size=9"
    MinimizedWindowFontNameXft =		"Tahoma:size=9,MS UI Gothic:size=9"
    ListBoxFontNameXft =				"Tahoma:size=9,MS UI Gothic:size=9"
    ToolTipFontNameXft =				"Tahoma:size=9,MS UI Gothic:size=9"
    ClockFontNameXft = 					"Tahoma:size=9,MS UI Gothic:size=9"
    TempFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
    ApmFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
    InputFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
    LabelFontNameXft =					"Tahoma:size=9,MS UI Gothic:size=9"
